filter:
    paths:
        - src/

before_commands:
    - 'composer install --no-interaction --prefer-source'
    - 'cp phpunit.xml.dist phpunit.xml'

tools:
    php_code_sniffer:
        config:
            standard: PSR2
    php_code_coverage:
        enabled: true
    php_loc: true
    php_analyzer: true
    php_pdepend: true

build:
    tests:
        override:
            -
                command: './bin/phpunit --coverage-clover=tests/coverage.xml'
                coverage:
                    file: 'tests/coverage.xml'
                    format: 'php-clover'
