language: php

sudo: false

php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - cp phpunit.xml.dist phpunit.xml
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; fi

script:
  - ./bin/phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
