language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - cp phpunit.xml.dist phpunit.xml

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
